apiVersion: apps/v1
kind: Deployment    #! Aca se define el tipo de archivo de configuración
metadata:
  name: mongo
  labels:
    app: mongo    #! Grupo al que pertenece el deployment 

#! Especificaciones para el deployment file
spec: 
  replicas: 1     #! Cantidad de pods
  selector:
    matchLabels:
      app: mongo    #! Grupo de pods que manejará el deployment

  template:
    metadata:
      labels:
        app: mongo  #! Grupo al que pertenecerán los pods creados en este deployment
    
    #! Especificaciones para los pods
    spec: 
      estartPolicy: Always
      
      #! Contenedor de la aplicación
      containers:
        - name: mongodb
          image: mongo:5.0
          imagePullPolicy: Always
          ports:
          - containerPort: 27017    #! Puerto de mongodb, sacado de documentación de dockerhub
          
          env:
            - name: MONGO_INITDB_ROOT_USERNAME      #! Nombre de la variable de entorno en el pod
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret    #! Nombre del archivo YAML.
                  key: mongo-user     #! Nombre de la key en el archivo YAML
            
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

          # #! Limites de CPU y RAM para el pod
          # resources:
          #   limits:
          #     cpu: "0.5"
          #     memory: "512Mi"   #! 512 MegaBytes
          #   requests:
          #     cpu: "0.1"
          #     memory: "256Mi"